// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// new_gauss_kern
NumericMatrix new_gauss_kern(const NumericMatrix newx, const NumericMatrix oldx, const double b);
RcppExport SEXP _KBAL_new_gauss_kern(SEXP newxSEXP, SEXP oldxSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix >::type newx(newxSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix >::type oldx(oldxSEXP);
    Rcpp::traits::input_parameter< const double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(new_gauss_kern(newx, oldx, b));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_KBAL_new_gauss_kern", (DL_FUNC) &_KBAL_new_gauss_kern, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_KBAL(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
